name: winepool_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  uuid: ^4.5.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.3
  ebs_plugin:
    path: ./ebs_plugin
  country_flags: ^4.1.0
  flutter_launcher_icons: ^0.14.2
  shimmer: ^3.0.0
  fl_chart: ^1.1.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  flutter_tesseract_ocr: ^0.4.30
  envied: ^1.3.2
  csv: ^6.0.0
  file_picker: ^8.0.3
  url_launcher: ^6.3.1
  image: ^4.6.0
  universal_html: ^2.2.4
  path_provider: ^2.1.5
  permission_handler: ^11.1.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^3.0.0
  envied_generator: ^1.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  analyzer: ^7.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/tessdata/
    - assets/tessdata/eng.traineddata
    - assets/tessdata/rus.traineddata
    - assets/tessdata_config.json
    - assets/csv_templates/

flutter_launcher_icons:
 android: true
 ios: true
 image_path: "assets/icons/WP_ico2.png"
